INSERT INTO COINS (ID,COIN_TYPE,AVAILABLE_COINS,VERSION) VALUES (100,'QUARTER', 16, 1);
INSERT INTO COINS (ID,COIN_TYPE,AVAILABLE_COINS,VERSION) VALUES (101,'DIME', 5, 1);
INSERT INTO COINS (ID,COIN_TYPE,AVAILABLE_COINS,VERSION) VALUES (102,'NICKEL', 8, 1);
INSERT INTO COINS (ID,COIN_TYPE,AVAILABLE_COINS,VERSION) VALUES (103,'PENNY', 10, 1);